# Generated by Django 5.1.6 on 2025-02-22 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categorybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.categorybase')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
            bases=('products.categorybase',),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('categorybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.categorybase')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcategories/', verbose_name='Изображение подкатегории')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
            bases=('products.categorybase',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('categorybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.categorybase')),
                ('image_small', models.ImageField(blank=True, null=True, upload_to='products/small/', verbose_name='Маленькое изображение продукта')),
                ('image_medium', models.ImageField(blank=True, null=True, upload_to='products/medium/', verbose_name='Среднее изображение продукта')),
                ('image_large', models.ImageField(blank=True, null=True, upload_to='products/large/', verbose_name='Большое изображение продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость продукта')),
                ('parent_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
            bases=('products.categorybase',),
        ),
    ]
